### ISSUE TITLE
小米3运行问题

### ISSUE THREAD

**Issue by ervincm** [zhongjihao/AVMediaCodecMP4#1]
你好，感谢你的代码分享。我在小米3上面运行你的程序，在点击结束的时候，有下面问题。即这一行：byte[] data = videoQueue.take(); //待编码的数据。想问，意思对audio编码取数据出错了吗?

1. java.lang.InterruptedException
2.    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:1988)
3.    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2022)
4.   at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
5.  at com.example.apadmin.cameraphoto.AVEncoder$1.run(AVEncoder.java:265)

**Comment by zhongjihao** [comment]
该问题我在我们平台手机上已经修复了，我这边没有小米，你更新下最新代码，在小米上试试，如果还有问题，请提供下程序运行的log
