### ISSUE TITLE
安装不了

### ISSUE THREAD

**Issue by SprrowZ** [zhongjihao/AVMediaCodecMP4#3]
Installation failed due to: 'Invalid File: /Users/zhaozhenguo/Desktop/demo/AVMediaCodecMP4/app/build/outputs/apk/ANDROID_MEDIACODEC_MP4/debug/v2.3.100.2201051940-ANDROID_MEDIACODEC_MP4-debug.apk'

**Comment by zhongjihao** [comment]
重新编译安装
